export const CREATERECIPE = 'CREATERECIPE';

export const LOGIN = 'LOGIN';

export const SEARCHING = 'SEARCHING';

export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP = 'SIGNUP';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';